grafana:
  adminPassword: "ChangeMe!"
  persistence:
    enabled: true
    size: 10Gi
  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    retention: 15d
    resources:
      requests: { cpu: 200m, memory: 1Gi }
      limits: { cpu: 1, memory: 2Gi }
  storageSpec:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
  service:
    type: LoadBalancer

alertmanager:
  alertmanagerSpec:
    resources:
      requests: { cpu: 100m, memory: 256Mi }
  config:
    route:
      receiver: 'slack'
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 2h
    receivers:
      - name: 'slack'
        slack_configs:
          - api_url: "https://hooks.slack.com/services/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"
            channel: '#alerts'
            send_resolved: true
            title: '{{ template "slack.default.title" . }}'
            text: >-
              *{{ .CommonLabels.alertname }}* in *{{ .CommonLabels.namespace }}*
  service:
    type: LoadBalancer
